# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# here start the non-default configuration
url: "https://archri.github.com/recipes"
collections:
  recipes:
    output: true

defaults:
  # set a helper property for images, so they can be filtered easily
  - scope:
      path: "assets/img"
    values:
      image: true
