# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# here start the non-default configuration
url: "https://archri.github.com/recipes"
collections:
  recipes:
    output: true

defaults:
  - scope:
      path: "_recipes"
    values:
      layout: "recipe"
